/**
 * This file is used to register the static domains for the custom protocols.
 * Static domains are domains that are served from the static files generated by Vite.
 * They are usually written in React.
 */

import type { Hono } from "hono/tiny";
import type { Context } from "hono";
import type { CustomProtocol } from "../types";
import { STATIC_DOMAINS } from "./config";
import { serveStaticDomainFile } from "@/controllers/sessions-controller/protocols/static-domains/serve-static";

export function registerStaticDomainsRoutes(protocol: CustomProtocol, app: Hono) {
  const domainInfos = STATIC_DOMAINS.filter((domainInfo) => domainInfo.protocol === protocol);
  if (domainInfos.length === 0) {
    return;
  }

  const handler = async (c: Context) => {
    const domain = c.req.param("domain");
    const path = c.req.param("path") ?? "/";

    for (const domainInfo of domainInfos) {
      if (!domain || domainInfo.hostname !== domain.toLowerCase()) {
        continue;
      }

      const actualType = domainInfo.actual.type;
      if (actualType === "route") {
        return await serveStaticDomainFile(c, path, {
          overrideRouteName: domainInfo.actual.route
        });
      } else if (actualType === "subdirectory") {
        return await serveStaticDomainFile(c, path, {
          extraBaseDir: domainInfo.actual.subdirectory
        });
      }
    }

    // Invalid domain, show error page
    // -300 is ERR_INVALID_URL (https://github.com/ccnokes/chrome-network-errors/blob/master/index.js)
    const errorPageURL = new URL("puerta://error");
    errorPageURL.searchParams.set("errorCode", "-300");
    errorPageURL.searchParams.set("url", c.req.url);
    errorPageURL.searchParams.set("initial", "1");
    return c.redirect(errorPageURL.toString());
  };

  app.get("/:domain", handler);
  app.get("/:domain/:path{.+}", handler);
}
